- name: setup bastion
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import vpc
      include_vars: bastion_setup.txt
    
    - name: import vpc setup
      include_vars: output_vars.txt
    
    - name: Create vprofile ec2 key
      ec2_key:
         name: vprofile_key
         region: "{{region}}"
      register: key_out

    - name: Save key
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create SG for bastion host
      ec2_group:
        name: Bastion_SG
        description: allow port 22 from anywhere
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastionsg_out
    
    - name: creating bastion host
      ec2:
        key_name: vprofile_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
            Name: "Bastion_host"
            Project: vprofile
            Owner: devops
        exact_count: 1
        count_tag:
            Name: "Bastion_host"
            Project: vprofile
            Owner:  devops
        group_id: "{{bastionsg_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out
      #