- name: setup bastion
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: import vpc
      include_vars: bastion_setup.txt
    
    - name: import vpc setup
      include_vars: output_vars.txt
    
    - name: Create vprofile ec2 key
      ec2_key:
         name: vprofile_key
      register: key_out

    - name: Save key
      copy:
        content: "{{key_out.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create SG for bastion host
      ec2_group:
        name: Bastion SG
        description: allow port 22 from anywhere
        vpc_id: "{{vpcid}}"
        profile: "{{ aws_profile }}"
        region: "{{region}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastionsg_out
    
    - name: creating bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 180