- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
   - name: Import VPC Variables
     include_vars: vpc_setup.txt

   - name: Create vprofile vpc
     ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}" 
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
     register: vpcout

   - debug:
       var: vpcout

   - name: create Public Subnet 1 in Zone1
     ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"
       cidr: "{{PubSub1Cidr}}"
       map_public: yes
       resource_tags:
         Name: vprofilesub1
     register: pubsub1_out

   - name: create Public Subnet 2 in Zone2
     ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone2}}"
       state: "{{state}}"
       cidr: "{{PubSub2Cidr}}"
       map_public: yes
       resource_tags:
         Name: vprofilesub2
     register: pubsub2_out

   - name: create Public Subnet 3 in Zone3
     ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone3}}"
       state: "{{state}}"
       cidr: "{{PubSub3Cidr}}"
       map_public: yes
       resource_tags:
         Name: vprofilesub3
     register: pubsub3_out

   - name: create Private Subnet 1 in Zone1
     ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone1}}"
       state: "{{state}}"
       cidr: "{{PrivSub1Cidr}}"
       map_public: yes
       resource_tags:
         Name: vprofileprivsub1
     register: privsub1_out
   
   - name: create Private Subnet 2 in Zone2
     ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone2}}"
       state: "{{state}}"
       cidr: "{{PrivSub2Cidr}}"
       map_public: yes
       resource_tags:
         Name: vprofileprivsub2
     register: privsub2_out

  
   - name: create Private Subnet 3 in Zone3
     ec2_vpc_subnet:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       az: "{{zone3}}"
       state: "{{state}}"
       cidr: "{{PrivSub3Cidr}}"
       map_public: yes
       resource_tags:
         Name: vprofileprivsub3
     register: privsub3_out
     
     
   - name: internet gateway
     ec2_vpc_igw:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       state: "{{state}}"
       resource_tags:
         Name: vprofileigw
     register: igw_out
  
   - name: set up pubic subnet route
     ec2_vpc_route_table:
       vpc_id: "{{vpcout.vpc.id}}"
       region: "{{region}}"
       tags:
         Name: Vprofile-PubRT
       subnets:
         - "{{ pubsub1_out.subnet.id }}"
         - "{{ pubsub2_out.subnet.id }}"
         - "{{ pubsub3_out.subnet_id }}"
       routes:
         - dest: 0.0.0.0/0
           gateway_id: "{{ igw_out.gateway_id }}"
     register: pubRT_out
  